all : 
	g++ -std=c++11 -O3 -g -w main.cpp -o dq -DNDEBUG

fast_dq:
	g++ -std=c++11 -O3 -g -w main.cpp -o fast_dq -DNDEBUG -DFAST

no_pre:
	g++ -std=c++11 -O3 -g -w main.cpp -o no_pre -DNDEBUG -D NO_prepro

clean:
	rm dq